
# For a more useful example, see:
# https://github.com/sarnobat/docker_images/tree/main/bison_helloworld

# conventions: https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html#Standard-Targets
# by default, make builds the first target
all:	clear
	echo "Building"
	g++ -Wall -Wextra -pedantic -O2 -o main main.cpp

clear:
	echo "Cleared"

